/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    'Fists': '拳头',
    'None': '无',
    'If you can use them to punch trees (not in this game though), then why not use them to punch your enemies?': '如果你可以用它们来击打树(不是在这个游戏中)那为什么不用它们来打你的敌人呢?',
    'Scissors': '剪刀',
    'Knife': '小刀',
    'Hammer': '锤子',
    'Headphones': '耳机',
    'mouse': '老鼠',
    'A basic kitchen knife that has been specifically modified to suit all your killing needs.': '一种基本的菜刀，经过特别改装，以满足你所有的杀戮需要。',
    'This pair of headphones can absorb much more damage against camels.': '这对耳机可以吸收更多来自骆驼的伤害。。',
    "Resets everything except speedrun record & cookies.": "重置除speedrun 记录和cookies 之外的所有内容。",
    "Resets game as if you have never played before.": "重置游戏，就像您以前从未玩过一样。",
    "SAVE GAME": "保存游戏",
    "Save the code somewhere save!": "将代码保存在某处保存！",
    "Seed": "种子",
    "SHARPEN KNIFE": "磨刀",
    "SHARPEN SCISSORS": "磨剪刀",
    "Show map info in game area": "在游戏区显示地图信息",
    "SMALL LOAN": "小额贷款",
    "Smartphone": "手机",
    "SOFT RESET": "软复位",
    "Sometimes less is more.": "有时少即是多。",
    "Speedrun Mode": "速通模式",
    "Speedrun Record (": "速跑记录 (",
    "The Forge": "锻造厂",
    "The Gold Factory": "黄金工厂",
    "The museum has a lot of paintings and literatures inside, you can read some old scripts stored here.": "博物馆里面有很多绘画和文献，你可以阅读一些存放在这里的旧手稿。",
    "The Shop": "商店",
    "The Temple": "寺庙",
    "The Unconventional Weapon": "非常规武器",
    "This game is not affiliated with any of the websites you can \"open\" in this game": "本游戏不隶属于您可以在本游戏中“打开”的任何网站",
    "to attack.": "去攻击。",
    "to be ready to do something, but you don't seem to know what that \"something\" is yet. When you know it, please come back here.": "准备做某事，但您似乎还不知道“某事”是什么。当你知道的时候，请回到这里。",
    "to eat apple (you can't eat apple while attacking).\n": "吃苹果（攻击时不能吃苹果）。\n",
    "To equip a weapon, open the inventory tab and click the text \"fists\". Then choose a weapon from the dropdown menu.": "要装备武器，请打开库存选项卡并单击文本“拳头”。然后从下拉菜单中选择一种武器。",
    "to shoot using infinity gun.": "使用无限枪射击。",
    "TOGGLE AUTOSAVE": "切换自动保存",
    "Training Center": "训练中心",
    "TURN OFF SPEEDRUN MODE": "关闭快速运行模式",
    "TURN ON SPEEDRUN MODE": "打开快速运行模式",
    "Twitter Emojis": "推特表情符号",
    "Use WASD / arrow keys to move, bump objects to interact.": "使用 WASD / 方向键移动，碰撞对象进行交互。",
    "Vanilla JS": "香草JS",
    "VIEW BOOKMARKS": "查看书签",
    "view changelog": "查看更新日志",
    "WEAPON": "武器",
    "where I list some other things that I have created just in case you're curious. It just feels amazing knowing that there people who are still playing something I made many years ago, so once again thank": "我在这里列出了我创建的其他一些东西，以防万一你好奇。知道还有人在玩我多年前制作的东西真是太棒了，再次感谢",
    "Which Subreddit?": "哪个子版块？",
    "World Warper": "世界大战",
    "you": "你",
    "You read the script, it says": "你读了剧本，它说",
    "You spawned in this world.": "你出生在这个世界。",
    "BUY SCISSORS": "买剪刀",
    "BUY TELEPORT MACHINE": "购买传送机",
    "Chat": "聊天",
    "Chickens!": "鸡！",
    "Chrome": "谷歌",
    "Chrome": "谷歌",
    "Click here for source and more info": "单击此处获取来源和更多信息",
    "Convenience Store": "便利店",
    "Cookies": "饼干",
    "Current Time": "当前时间",
    "Damage": "伤害",
    "Damage Reduction": "减少伤害",
    "Defense": "防御",
    "Did you know that turning a blue heart into a potion gives you more max HP than the blue heart itself? To make a blue heart potion, you need a blue heart (obviously) and a shiny heart, also you have to have a dragon armor to make it.": "您是否知道将蓝心变成药水可以比蓝心本身提供更多的最大 HP？要制作蓝心药水，你需要一颗蓝心（显然）和一颗闪亮的心，而且你必须有龙盔甲才能制作。",
    "directions_run": "方向_运行",
    "DO SOME MEDITATION": "做一些冥想",
    "DRAGON ARMOR": "龙甲",
    "Dragon skins make a really good armor, you can craft one if you have enough of these skins. Your knife also needs to have at least 50,000 damage so we can use it to cut the dragon skin.": "龙皮是一件非常好的盔甲，如果你有足够的龙皮，你可以制作一个。你的刀也需要有至少 50,000 的伤害，这样我们才能用它来切割龙皮。",
    "EXPORT SAVE AS TEXT": "导出另存为文本",
    "gold": "金币",
    "gold.": "金币。",
    "gold) Increases your knife's damage.": "金）增加你的刀的伤害。",
    "gold) Increases your scissors' damage.": "金）增加剪刀的伤害。",
    "HEAD": "头",
    "Here, we train beginners": "在这里，我们训练初学者",
    "IMPORT SAVE FROM TEXT": "从文本导入保存",
    "In order to view the console in Safari, you have to enable the \"Show Develop menu in menu bar\" setting in the \"Advanced\" pane of Safari's preferences": "为了在 Safari 中查看控制台，您必须在 Safari 首选项的“高级”窗格中启用“在菜单栏中显示开发菜单”设置",
    "Increases fists' damage": "增加拳头伤害",
    "Increases max hp by one": "最大 生命值 增加 1",
    "INFINITY GUN": "无限枪",
    "Inventory": "库存",
    "It is said that this gun is only available for purchase from the developer himself. To do so, open your browser's developer console (open the \"keyboard shortcuts\" section to see how) and type in this command": "据说这把枪只能从开发商自己那里购买。 为此，请打开浏览器的开发者控制台（打开“键盘快捷键”部分以查看操作方法）并输入此命令",
    "It seems that your hands must be stronger to be able to use the forge.": "看来你的手必须更强壮才能使用锻造。",
    "It would be appreciated if you disable adblock!": "如果您禁用广告拦截，我们将不胜感激！",
    "ITEMS": "物品",
    "Keyboard Shortcuts": "键盘快捷键",
    "LARGE LOAN": "大额贷款",
    "Level": "等级",
    "Levels & XP": "等级和经验",
    "Map": "地图",
    "Material Design Lite": "材料设计精简版",
    "Material Warrior": "物质战士",
    "Meditate": "幽思",
    "Message from the Developer (December 2021": "来自开发者的消息（2021 年 12 月）",
    "MS Paint Shop": "微软油漆店",
    "Museum": "博物馆",
    "MY FIRST MURDER WEAPON!!!(Material Warrior Ep 1": "我的第一个谋杀武器！！！（材料战士第 1 集",
    "Old Script": "旧脚本",
    "PAY LOAN": "支付贷款",
    "PUNCH A DUMMY": "打一个假人",
    "BUY A SMARTPHONE": "购买智能手机",
    "BUY AN APPLE": "购买一个苹果",
    "BUY HEART ARMOR": "购买心之盔甲",
    "BUY MAGIC HAT": "购买魔法帽",
    "A House": "一个房子",
    "A Package!": "一套！",
    "About": "关于",
    "About this game": "关于这个游戏",
    "Add a Bookmark": "添加书签",
    "ADD TO BOOKMARKS": "添加到书签",
    "Bank": "银行",
    "Battle!": "战斗！",
    "blog post I made": "我发表的博文",
    "BLUE HEART POTION": "蓝心药水",
    "BODY": "身体",
    "Bookmarks": "书签",
    "BUY 10 APPLES": "买 10 个苹果",
    "BUY A BLUE HEART": "买一颗蓝心",
    "BUY A KNIFE": "买一把刀",
    "BUY A PAIR OF HEADPHONES": "买一副耳机",
    "Activating speedrun mode will soft reset the game (all progress will be lost except speedrun record and cookies). A timer will start automatically and stops after the game is finished. Turning off speedrun mode won't reset your progress, but you will have to soft reset the game if you want to activate speedrun mode again. Closing the game will turn off the speedrun mode.": "激活速通模式将软重置游戏（除速通记录和 cookie 外，所有进度都将丢失）。 计时器将自动启动并在游戏结束后停止。 关闭速通模式不会重置您的进度，但如果您想再次激活速通模式，则必须软重置游戏。 关闭游戏将关闭速通模式。",
    "? gold\n": "?黄金\n",
    "? kills left to run away again": "?击杀 距离再次逃跑",
    "? left\n": "?左\n",
    "(Level": "（等级",
    "# of alien2": "#外星人2",
    "# of camel1": "#骆驼1",
    "# of camel2": "#骆驼2",
    "# of dragons": "# 龙",
    "# of ghosts": "# 鬼魂",
    "# of goats": "#山羊",
    "# of mice": "# 白老鼠",
    "# of rats": "# 灰老鼠",
    "# of snakes": "#蛇",
    "ATTACK!": "攻击！",
    "Autosave is automatically set to on each time the page is opened.": "每次打开页面时，自动保存都会自动设置为开启。",
    "Check out my other (older) games": "查看我的其他（较旧的）游戏",
    "Click here to read": "点击这里阅读",
    "CLOSE": "关闭",
    "Cmd + Opt + C": "Cmd + 选项 + C",
    "CRAFT AND DRINK THE POTION": "制作和饮用药水",
    "CRAFT ARMOR": "制作盔甲",
    "Don't forget to use the items you bought!": "不要忘记使用您购买的物品！",
    "EAT APPLE\n\t": "吃苹果\n\t",
    "ENTER PORTAL": "进入门户",
    "Experiences can be gained by killing enemies. Each time you level up you will gain a new ability": "可以通过击杀敌人获得经验。每次升级你都会获得一个新的能力",
    "F12, then click on the \"Console\" tab": "F12，然后单击“控制台”选项卡",
    "GitHub Repo": "GitHub 仓库",
    "GIVE PIZZA": "送披萨",
    "Hi! If you're reading this I just would like to thank you for playing this game up until now, honestly I didn't expect that this game still has some players even 6+ years after its release!": "你好！如果您正在阅读本文，我只想感谢您玩到现在为止，老实说，我没想到这款游戏即使在发布 6 年多之后仍然有一些玩家！",
    "How to open the developer console": "如何打开开发者控制台",
    "HP": "生命值",
    "I also would like to thank the people who have uploaded gameplay videos of this game, it definitely feels \"wow\" seeing gameplay videos of my own game!\n": "还要感谢上传这款游戏的游戏视频的人，看到我自己游戏的游戏视频绝对有“哇”的感觉！\n",
    "If you enjoyed this game you can check out several other games I have made in the past:\n": "如果您喜欢这款游戏，您可以查看我过去制作的其他几款游戏：\n",
    "If you have an unpaid loan, you can't visit houses in this area until you pay your loan (you still can visit the shop, training center, etc.).": "如果您有未偿还的贷款，在您还清贷款之前，您不能访问该地区的房屋（您仍然可以访问商店、培训中心等）。",
    "Internet Explorer": "IE浏览器",
    "Mac OS: Cmd + Opt + J": "Mac 操作系统：Cmd + Opt + J",
    "Mac OS: Cmd + Opt + K": "Mac 操作系统：Cmd + Opt + K",
    "NEXT": "下一个",
    "Press": "按",
    "Read the new": "阅读新消息",
    "RUN AWAY": "逃跑",
    "Safari": "苹果浏览器",
    "SHOOT\n": "射击\n",
    "So, you have already known about \"the negative zone\" and the creature inside, right? We are here to help you prepare to defeat that creature, however you will need some items": "所以，你已经知道“负面区域”和里面的生物了吧？我们在这里帮助您准备击败那个生物，但是您需要一些物品",
    "STOP MEDITATING": "停止冥想",
    "Subreddit": "子版块",
    "TAKE ITEM": "拿取物品",
    "The teleport machine will appear near your respawn area.": "传送机将出现在您的重生区域附近。",
    "This game has keyboard shortcuts for battle actions": "这个游戏有战斗动作的键盘快捷键",
    "This game uses": "这个游戏使用",
    "THROW GOLD\n\t": "扔金币\n\t",
    "We only sell items made purely with MS Paint.": "我们只销售纯粹用 微软画笔 制作的物品。",
    "Weapon": "武器",
    "Windows: Ctrl + Shift + J": "视窗：Ctrl + Shift + J",
    "Windows: Ctrl + Shift + K": "视窗：Ctrl + Shift + K",
    "XP": "经验值",
    "You can also check out this": "你也可以看看这个",
    "You could pay your loan if you have enough gold.": "如果你有足够的黄金，你就可以偿还贷款。",
    "You could take a loan from the bank if you wanted to.": "如果你愿意，你可以从银行贷款。",
    "2021 message!": "2021 消息!",
    "Ouch! Cactus hurts!": "哎哟! 仙人掌，真疼！",
    "A Camel!": "一只骆驼！",
    "miss": "未命中",
    "You are killed by a camel.": "你被骆驼杀死了。",
    "You can run away now": "你现在可以逃跑了",
    "\"Don't ask me how I can live in this climate, but maybe I can help you a little bit.\"": "\“别问我怎么能在这种气候下生活，但也许我可以帮你一点。”",
    "\"Good Luck!\"": "\“祝你好运！\”",
    "\"Hi there! You seem to be new here.\"": "\"你好！你好像是新来的。\"",
    "\"The further you go from here the enemies get harder, but they give you more gold.\"": "\“你离这里越远，敌人就越难对付，但他们会给你更多的金币。\”",
    "A Mouse!": "一只白老鼠！",
    "gold and gained": "金币并获得",
    "Level up! Check the sidebar to see your new ability.": "升级！ 检查侧边栏以查看您的新能力。",
    "You killed a mouse for": "你杀了一只老鼠获得了 ",
    "Extra gold for every kill to the same enemy without dying.": "在不死亡的情况下，每次击杀同样的敌人都会获得额外的金币。",
    "Nothing special :(": "没什么特别的 :(",
    "Penguin": "企鹅",
    "xp.": "经验值.",
    "A Rat!": "一只灰老鼠！",
    "You are killed by a Mouse.": "你被白老鼠杀死了。",
    "You are killed by a rat.": "你被灰老鼠杀死了。",
    "This package contains 1 xp. There are 10 similar packages in this area, find them all!": "这个箱子包含了 1 经验值。 该地区有10个类似的箱子，全部找到！",
    "Your got": "你得到了 ",
    "You bought a pair of headphones for": "你买了一副耳机",
    "Blue Heart": "蓝心",
    "Less chance to miss when attacking.": "减少攻击时未命中的几率。",
    "Blue Heart Potion": "蓝心药水",
    "Dragon Armor": "龙甲",
    "Dragon skins are too precious to throw, maybe you will find them useful later.": "龙皮太珍贵了，不能扔，也许你以后会发现它们有用。",
    "Eating an apple heals you during a battle. Can't eat them while attacking though.": "在战斗中吃一个苹果可以治愈你。 攻击时不能吃。",
    "Enemies miss more when attacking.": "敌人在攻击时会出现更多地未命中。",
    "Heart Armor": "心之铠甲",
    "Infinity Gun": "无限枪",
    "It looks like this house is locked. You knock the door but there are no replies. Probably the owner is away.": "这房子好像上锁了。 你敲门，但没有回应。 估计楼主不在了。",
    "Magic Hat": "魔法帽",
    "These pizzas look and smell delicious, unfortunately you can't enjoy their gloriousness.": "这些比萨看起来和闻起来都很美味，不幸的是你不能享受它们的光彩。",
    "This armor is disguised as a normal t-shirt, but don't be deceived by it's look.": "这件盔甲伪装成一件普通的 T 恤，但不要被它的外表所欺骗。",
    "This hat is mostly just for style, but at least it protects you a little bit.": "这顶帽子主要是为了风格，但至少它可以保护你一点。",
    "This heart increases your max hp by 400 and changes your respawn point. Your max hp won't decrease if you don't have the heart anymore.": "这颗心使您的最大 hp 增加 400 并改变您的重生点。 如果你不再有心脏，你的最大 hp 不会减少。",
    "This lovely piece of armor heals you each time you attack an enemy.": "每次攻击敌人时，这件可爱的盔甲都会治愈你。",
    "This shiny heart makes you heal faster when you are not in a battle. The effect of this heart persists even after you don't have it anymore.": "这颗闪亮的心脏让你在不参加战斗时恢复得更快。 即使你不再拥有它，这颗心的效果仍然存在。",
    "Unlocks the ability to run away once for each 10 kills.": "解锁每击杀 10 次逃跑一次的能力。",
    "Unlocks the ability to throw gold against enemies.": "解锁向敌人投掷金币的能力。",
    "You bought 10 apples for": "你买了 10 个苹果",
    "You bought an apple for": "你买了一个苹果",
    "You took a small loan of a million gold.": "你借了一笔 100万 金币的小额贷款。",
    "A Space Invaders Alien Thingy!": "一个太空侵略者外星人的东西！",
    "Infinity": "无限",
    "You killed a space invaders alien thingy for": "你杀死了一个太空入侵者外星人的东西",
    "You paid your loan.": "你还清了贷款。",
    "Your bought a blue heart for": "你买了一颗蓝心花了 ",
    "Unlocks the ability to dodge from enemy attacks for 3 seconds.": "解锁躲避敌人攻击的能力，持续 3 秒。",
    "Although it is weird to use scissors as a weapon, at least it works.": "虽然用剪刀作为武器很奇怪，但至少它是有效的。",
    "If you are the pizza deliverer, please send everyone else's pizzas first then send me the last one.": "如果你是送披萨的，请先送别人的披萨，再送最后一个。",
    "In front of the house there's a message": "房子前面有一条消息",
    "blue heart potion(s) and now you have": "蓝心药水，现在你有",
    "max HP!": "最大生命值！",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "settings": "settings",
    "keyboard": "keyboard",
    "help": "help",
    "explore": "explore",
    "Firefox": "Firefox",
    "menu": "menu",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\t\t\t": "\t\t\t",
    "\t\t": "\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "READ OLD SCRIPT ": "阅读旧脚本",
    "Game Version: ": "游戏版本: ",
    "ATTACK! (": "攻击! (",
    "Apple x": "苹果 x",
    "Dragon Corpse x": "龙尸 x",
    "Pizza x": "披萨 x",
    "Shiny Heart x": "闪亮的心 x",
    "Blue Heart x": "蓝心 x",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Game autosaves in (.+) seconds.$/, '游戏将在 $1 秒内自动保存。'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Attempt (.+)\: Success \| Material Warrior Speed Run Personal Bests$/, '尝试 $1：成功 \| 材料勇士速通 个人最佳成绩'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) gold$/, '$1 金币'],
    [/^([\d\.,]+) left$/, '$1 剩余'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);